version: "3.1"
services:
  db:
    container_name: pgsql
    image: postgres:15-alpine
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: Tv9WT0ZAbUlPh0eP
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
